# Generated by Django 3.0.2 on 2020-03-02 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200227_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Category'),
            preserve_default=False,
        ),
    ]
