# Generated by Django 3.0.2 on 2020-03-22 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200302_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='group_field',
        ),
        migrations.AlterField(
            model_name='field',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fields', to='api.Category'),
        ),
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fields', to='api.Type'),
        ),
        migrations.AlterField(
            model_name='fieldvalue',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='field_values', to='api.Field'),
        ),
        migrations.AlterField(
            model_name='fieldvalue',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='field_values', to='api.Product'),
        ),
        migrations.DeleteModel(
            name='GroupField',
        ),
    ]
