# Generated by Django 3.0.2 on 2020-04-08 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200322_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo_url',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
